### ISSUE TITLE
Reproducible crashes when fetching additional search results (from adb logcat: Gravatar issues).

### ISSUE THREAD

**Issue by vifo** [zostay/CPAN-Sidekick#16] opened 2012-09-02 12:05 UTC
When displaying search results, as soon as I try to load additional results, the app reproducibly crashes.

```
adb logcat:

I/BugSenseHandler( 3664): Registering default exceptions handler
D/BugSenseHandler( 3664): Looking for exceptions in: /data/data/com.qubling.sidekick/files
D/BugSenseHandler( 3664): Found 0 stacktrace(s)
I/ActivityManager(  200): START {cmp=com.qubling.sidekick/.ui.module.ModuleSearchActivity} from pid 3664
W/InputManagerService(  200): Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@40e0f968 (uid=10117 pid=1237)
I/ActivityManager(  200): Displayed com.qubling.sidekick/.ui.module.ModuleSearchActivity: +127ms (total +275ms)
D/dalvikvm(  398): GC_CONCURRENT freed 1717K, 61% free 3932K/9927K, paused 2ms+4ms
D/dalvikvm(  200): GC_EXPLICIT freed 1369K, 36% free 10342K/16071K, paused 2ms+5ms
I/HttpClientManager( 3664): Using AndroidHttpClient
D/dalvikvm( 3664): GC_CONCURRENT freed 2253K, 40% free 5002K/8323K, paused 2ms+3ms
W/InputManagerService(  200): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@4109fc30
D/dalvikvm( 3664): GC_CONCURRENT freed 1613K, 39% free 5110K/8323K, paused 8ms+4ms
D/dalvikvm( 3664): GC_FOR_ALLOC freed 24K, 33% free 5627K/8323K, paused 16ms
D/dalvikvm( 3664): GC_FOR_ALLOC freed <1K, 30% free 5987K/8519K, paused 16ms
W/GravatarFetcher( 3664): Gravatar request took too long, aborting fetch: https://secure.gravatar.com/avatar/487cec9cf48d061d509d6933a8a06529?s=92&d=identicon
W/dalvikvm( 3664): threadid=19: thread exiting with uncaught exception (group=0x40a3d1f8)
D/BugSenseHandler( 3664): java.lang.RuntimeException: Gravatar took too long
D/BugSenseHandler( 3664):   at com.qubling.sidekick.fetch.other.GravatarFetcher$1.run(GravatarFetcher.java:125)
D/BugSenseHandler( 3664):   at java.util.Timer$TimerImpl.run(Timer.java:284)
E/AndroidRuntime( 3664): FATAL EXCEPTION: Timer-4
E/AndroidRuntime( 3664): java.lang.RuntimeException: Gravatar took too long
E/AndroidRuntime( 3664):    at com.qubling.sidekick.fetch.other.GravatarFetcher$1.run(GravatarFetcher.java:125)
E/AndroidRuntime( 3664):    at java.util.Timer$TimerImpl.run(Timer.java:284)
W/ActivityManager(  200):   Force finishing activity com.qubling.sidekick/.ui.module.ModuleSearchActivity
I/DemoService( 1237): DiyScheduer.onStart
I/ActivityManager(  200): No longer want android.process.media (pid 3009): hidden #16
W/GravatarFetcher( 3664): Gravatar request took too long, aborting fetch: https://secure.gravatar.com/avatar/18636b8c103162787de8d2b1728cf076?s=92&d=identicon
W/dalvikvm( 3664): threadid=20: thread exiting with uncaught exception (group=0x40a3d1f8)
D/BugSenseHandler( 3664): java.lang.RuntimeException: Gravatar took too long
D/BugSenseHandler( 3664):   at com.qubling.sidekick.fetch.other.GravatarFetcher$1.run(GravatarFetcher.java:125)
D/BugSenseHandler( 3664):   at java.util.Timer$TimerImpl.run(Timer.java:284)
I/Process ( 3664): Sending signal. PID: 3664 SIG: 9
I/ActivityManager(  200): Process com.qubling.sidekick (pid 3664) has died.
W/InputManagerService(  200): Got RemoteException sending setActive(false) notification to pid 3664 uid 10162
```

System Information:

```
CyanogenMod 9.1 on Samsung Galaxy GT-9100G
Build: cm_i9100g-userdebug 4.0.4 IMM76L eng..20120828.161614 test-keys
Kernel: Linux version 3.0.33-CM-g6f8e729 (blinky-ghost@cyanogenmod) (gcc version 4.4.3 (GCC) ) #1 SMP PREEMPT Tue Aug 28 16:22:34 PDT 2012
Command line: root=/dev/mmcblk0p1 rw rootdelay=2 init=/init vram=15M omapfb.vram=0:5M androidboot.hardware=t1 switch_sel=1 androidboot.emmc_checksum=3 sec_debug.enable=0 sec_debug.enable_user=0 androidboot.debug_level=0x4f4c mem=512M@0x80000000 mem=512M@0xa0000000 vmalloc=144m console=sec_log_buf loglevel=0 androidboot.mode=reboot_normal bootmode=0 sec_log=2052K@0x9fdff000 sec_bootfb=8M@0xaf800000 lcd_panel_id=1
```

**Comment by vifo** [comment] 2012-09-02 12:06
Just realized that this seems to be a duplicate of #5.

**Comment by zostay** [comment] 2012-12-08 16:27
This is a duplicate of #11, which has been fixed.

**Closed as completed by zostay** 2012-12-08 16:27 UTC
Labels: Duplicate
